  " Personal vimrc file                                                               
                                                                                      
  syntax on " for syntax highlighting                                                 
                                                                                      
  set noswapfile " UNSAVED WORK WILL BE LOST                                          
                                                                                      
  set spell spelllang=en_us                                                           
  set autoindent                                                                      
  set tabstop=2 softtabstop=2                                                         
  set shiftwidth=2                                                                    
  set expandtab                                                                       
  set ignorecase                                                                      
  set showmatch                                                                       
  set hlsearch                                                                        
  set ttyfast                                                                         
  set number                                                                          
  set colorcolumn=100                                                                  
  set nowrap                                                                          
  " Natural split opening                                                             
  set splitbelow                                                                      
  set splitright                                                                      
       
  " Set Encoding for Nerd Fonts    
  set encoding=utf-8    
  set fileencoding=utf-8    
       
       
  " ATTEMPT TO INSTALL PLUG                                                           
  if empty(glob('~/.vim/autoload/plug.vim'))                                          
    silent !curl -flo ~/.vim/autoload/plug.vim --create-dirs                          
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim           
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC                           
  endif                                                                               
                                                                                      
  call plug#begin('~/.vim/plugged')                                                   
                                                                                      
  Plug 'morhetz/gruvbox'                                                              
  Plug 'preservim/nerdtree'                                                           
  Plug 'vim-airline/vim-airline'    
  Plug 'vim-airline/vim-airline-themes'    
  Plug 'junegunn/fzf', {'do': {-> fzf#install() } }    
  Plug 'junegunn/fzf.vim'    
  " Plug 'ryanoasis/vim-devicons'    
         
  call plug#end()    
          
  colorscheme gruvbox    
  set background=dark    
       
  let g:airline_extensions = ['branch']    
  let g:airline#extensions#branch#enabled = 1
